CRS = CUSTOMER REQUIREMENT SPECIFICATION.
 SRS=SOFTWARE REQUIREMENT SPECIFICATION.
 KT = KNOWLEDGE TRANSFER
 POSTMAN
SDLC SOFTWARE DEVELOPMENT LIFE CYCLE
1.PLANNING
2.IMPLEMENTATION
3.TESTING
4.DOCUMENT
5.DEPLOYMENT
APPLICATION
    1.WEB APPLICATION
        APPLICATION WHICH RUNS ON BROWSER.
        1.DOMAIN NAME
        2.WEB HOSTING
        IPV4 4.3 BILLION
        IPV6 
        HTTP (HYPER TEXT TRANSFER PROTOCOL) 80
        https 443 
        FIREWALL   
        GET (TO GET THE DATA FROM THE SERVER)
        POST (TO INSERT A DATA IN THE SERVER)
    2.MOBILE APPLICATION
        INTAGRAM,FACEBOOK
        STORE: ANDROID(PLAY STORE).APK, IOS(APP STORE)
    3.DESKTOP APPLICATION
        WORD,EXCEL,POWERPOINT,BROWSER(CHROME,FIREOX,EDGE,SAFARI).
        MICROSOFT STORE.
6.ONGOING MAINTAINANCE AND SUPPORT

1.PLANNING
1. DFD
    LEVEL 0 (DO DATABASE INFO)
    LEVEL 1,2 (WITH DATABASE INFO)
2. FLOWCHART (GRAPHICAL REPRESENTATION OF PROGRAM)
    TYPES OF FLOWCHART
    1.LINEAR
    2.BRANCHING 
    3.LOOPING
3. USE CASE DIAGRAM
ALGORITHM
STEP 1:START
STEP 2:INPUT I=3,J=2
STEP 3: I>J?
STEP 4: IF TRUE PRINT I IS GREATER
STEP 5: IF FALSE PRINT J IS GREATER
STEP 6: STOP.
TIME COMPLEXITY
SPACE COMPLEXITY
