CRS = CUSTOMER REQUIREMENT SPECIFICATION.
 SRS=SOFTWARE REQUIREMENT SPECIFICATION.
 KT = KNOWLEDGE TRANSFER
 POSTMAN
SDLC SOFTWARE DEVELOPMENT LIFE CYCLE
1.PLANNING
2.IMPLEMENTATION
3.TESTING
4.DOCUMENT
5.DEPLOYMENT
APPLICATION
    1.WEB APPLICATION
        APPLICATION WHICH RUNS ON BROWSER.
        1.DOMAIN NAME
        2.WEB HOSTING
        IPV4 4.3 BILLION
        IPV6 
        HTTP (HYPER TEXT TRANSFER PROTOCOL) 80
        https 443 
        FIREWALL   
        GET (TO GET THE DATA FROM THE SERVER)
        POST (TO INSERT A DATA IN THE SERVER)
    2.MOBILE APPLICATION
        INTAGRAM,FACEBOOK
        STORE: ANDROID(PLAY STORE).APK, IOS(APP STORE)
    3.DESKTOP APPLICATION
        WORD,EXCEL,POWERPOINT,BROWSER(CHROME,FIREOX,EDGE,SAFARI).
        MICROSOFT STORE.
6.ONGOING MAINTAINANCE AND SUPPORT

